[package]
name = "nanostat"
version = "0.1.0"
authors = ["Coda Hale <coda.hale@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benches"
harness = false
